# Solon Configuration
solon.name: CMS-Scaffold
solon.logging.logger:
  "org.noear":
    level: INFO

# Server configuration
server.port: 8080
server.request.maxBodySize: 20mb

# BeetlSQL Configuration
beetlsql.dbStyle: "org.beetl.sql.core.db.MySqlStyle"
beetlsql.sqlPath: "beetlsql"
beetlsql.nameConversion: "org.beetl.sql.core.UnderlinedNameConversion"

# Database Configuration
beetlsql.db:
  url: jdbc:mysql://localhost:3306/cms_scaffold?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: root
  maxActive: 20
  initialSize: 5
  minIdle: 5
  maxWait: 60000

# Beetl Template Configuration
beetl:
  templatesPath: "templates/"

# Session Configuration
server.session.timeout: 7200
server.session.state.jwt: "cms-scaffold-session-key-2024"
